Add industry material demands
iiasa/prisma-workflow pull request #4
Opened 2024-12-18 11:12 UTC by macflo8

2024-12-19 12:46 UTC, macflo8 commented
@danielhuppmann please review 🙏🏻

2024-12-19 13:17 UTC, danielhuppmann reviewed
Thanks, some suggestions below to make sure that this will be compatible with common-definitions.

2024-12-19 13:17 UTC, danielhuppmann commented on definitions/variable/industry/tag_demand_sectors.yaml
> +    - Electricity|{Generation Technology}:
Nested tag lists are not yet supported

2024-12-19 13:17 UTC, danielhuppmann commented on definitions/variable/industry/tag_chemical_commodities.yaml
> +        tier: "1"
This is still using an outdated approach for tier-assigment, please remove or use the new approach.

- In the variable, assign a tier as an integer.
- In the tag list, you can use `^1` or `^2` to increase the tier-number for that tag-item.

So in this case, if you have

```yaml
- Demand|Chemicals|{Chemicals Commodity}:
     description: Demand of {Chemicals Commodity}
     unit: Mt/yr
     tier: 2
```
and a tag-list:
```yaml
- Chemicals Commodity:
     - Ammonia:
         description: ammonia (NH3), precursor chemical for nitrogen fertilisers
   - Nitrogen Fertilizer:
         description: single-nutrient nitrogen fertilizers and nitrogen containing
           multi-nutrient fertilizers
         tier: ^1
```
the demand for ammonia has tier 2 and demand for nitrogen fertilizer is tier 3.

Please do not use tier 1 unless it is mandatory for models to report this variable in all PRISMA scenarios.

2024-12-19 13:17 UTC, danielhuppmann commented on definitions/variable/industry/demand.yaml
> +- Demand|Iron and Steel|Steel:
Suggest to rename this to "Material Demand" or similar for consistency with "Agricultural Demand" and "Forestry Demand" in common-definitions.

2024-12-19 13:17 UTC, danielhuppmann commented on definitions/variable/industry/tag_demand_sectors.yaml
> +        description: transport sector
```suggestion
        description: transportation sector
```

2024-12-19 13:17 UTC, danielhuppmann commented on definitions/variable/industry/tag_demand_sectors.yaml
> +        description: mobility infrastructure
Please clarify what is included in mobility infrastructure and how it differs from transportation

2024-12-19 13:17 UTC, danielhuppmann commented on definitions/variable/industry/tag_generation_technologies.yaml
> +        description: wind power plants
```suggestion
        description: wind turbines
```

2024-12-20 09:35 UTC, macflo8 commented
@danielhuppmann Thanks for the suggestions! All of them should be incorporated now. If there are no other remaining issues, this would be ready for merging from my side.

2025-01-10 09:49 UTC, danielhuppmann requested changes
Looks good overall, a few suggestions inline.

2025-01-10 09:49 UTC, danielhuppmann commented on definitions/variable/industry/tag_demand_sectors.yaml
> +          description: electricity generation with solar PV
In **common-definitions**, "Electricity|Solar" includes both PV and CSP. And maybe add sub-categories to distinguish if this is really necessary...
```suggestion
          description: electricity generation with solar photovoltaics and concentrated solar power
```

2025-01-10 09:49 UTC, danielhuppmann commented on definitions/variable/industry/tag_demand_sectors.yaml
> +          description: electricity generation with biomass power plants
Would it make sense to change the decsription to "construction of biomass power plants"? Also in the variables below...

2025-01-10 09:49 UTC, danielhuppmann commented on definitions/variable/industry/tag_demand_sectors.yaml
> +    - Transportation:
As a complement to the suggestion below.
```suggestion
    - Transportation|Vehicle Stock:
```

2025-01-10 09:49 UTC, danielhuppmann commented on definitions/variable/industry/tag_demand_sectors.yaml
> +    - Infrastructure|Mobility:
I'm hesitant to introduce a new term "Mobility", which might cause more confusion than it helps to avoid ambiguity. So I suggest to make that an explicit sub-category of "Transportation" instead.
```suggestion
    - Transportation|Infrastructure:
```

2025-01-10 11:27 UTC, volker-krey commented on definitions/variable/industry/tag_demand_sectors.yaml
> +    - Infrastructure|Mobility:
I don't have a strong feeling about 'Mobility' vs. 'Transportation', but would suggest to keep the order 'Infrastructure|Transportation' as there are other infrastructure types (e.g., water) that could be added.

2025-01-10 11:38 UTC, danielhuppmann commented on definitions/variable/industry/tag_demand_sectors.yaml
> +    - Infrastructure|Mobility:
I also considered that, but we also have "Electricity|Transmission and Distribution" (in the same file), so there, infrastructure is a sub-component of electricity. Not sure which other possible types of infrastructure we have beyond energy, transportation, and water? Buidlings? Telecom?

2025-01-14 06:32 UTC, danielhuppmann approved these changes
Looks good, thanks!

2025-01-14 06:33 UTC, merged